### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by Heahmund** [vitor251093/resurrection-capsule#15]
Can someone tell me if the project is live or not? If it’s not, what was the reason? I accidentally found it today and think it’s a good pet project, but I’m a bit concerned it might be tricky for me since I last used C ten years ago.

**Comment by Splitwirez** [comment]
Yes, Resurrection Capsule is absolutely still alive.

**Comment by Heahmund** [comment]
Thank you for your response! I will work on refreshing my skills so that I can assist with that
